config/routes.rb
Rails.application.routes.draw do
  resources :tweeets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "tweeets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweeet.rb
class Tweeet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweeets_controller.rb
class TweeetsController < ApplicationController
  before_action :set_tweeet, only: %i[ show edit update destroy ]

  # GET /tweeets or /tweeets.json
  def index
    @tweeets = Tweeet.all.order(created_at: :desc)
    @tweeet = Tweeet.new
  end

  # GET /tweeets/1 or /tweeets/1.json
  def show
  end

  # GET /tweeets/new
  def new
    @tweeet = Tweeet.new
  end

  # GET /tweeets/1/edit
  def edit
  end

  # POST /tweeets or /tweeets.json
  def create
    @tweeet = Tweeet.new(tweeet_params)

    respond_to do |format|
      if @tweeet.save
        format.html { redirect_to @tweeet, notice: "Tweeet was successfully created." }
        format.json { render :show, status: :created, location: @tweeet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweeets/1 or /tweeets/1.json
  def update
    respond_to do |format|
      if @tweeet.update(tweeet_params)
        format.html { redirect_to @tweeet, notice: "Tweeet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweeet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweeets/1 or /tweeets/1.json
  def destroy
    @tweeet.destroy
    respond_to do |format|
      format.html { redirect_to tweeets_url, notice: "Tweeet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweeet
      @tweeet = Tweeet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweeet_params
      params.require(:tweeet).permit(:tweeet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweeets_helper.rb
module TweeetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twittter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification text-primary">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification text-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <!-- Bootstrap 5 Navbar -->
    <nav class="navbar navbar-expand-lg navbar-primary bg-primary">
       <div class="container-fluid">
          <%= link_to root_path, class: "nav-item" do %>
            <h4 class="title text-white">Twittter</h4>
          <% end %>
          <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarSupportedContent">
            <%= link_to 'New Tweeet', new_tweeet_path, class: "btn bg-light text-primary" %>
            <p class="text-white my-0 mx-2">Sign Up</p>                   
          </div>
       </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/tweeets/_feed.html.erb
<div class="section d-flex justify-content-center">
  <div>
    <h4 clas="trends">Trending</h4>
    <div class="card gravatar">
      <div>
        <img src="http://www.gravatar.com/avatar" class="card-img-top rounded-circle" alt="foto" style="width: 5rem"; >
      </div>
    </div>
  </div>

  <div class="card">
    <% @tweeets.each do |tweeet| %>
      <div class="d-flex tweet-details">
        <div class="card-image avatar">
          <img src="http://www.gravatar.com/avatar" class="card-img-left rounded-circle" alt="foto">
        </div>

        <div class="card-body d-flex flex-column">
          <div>
            <p class="card-text"><%= tweeet.tweeet %></p>
          </div>
          <div class="icons d-flex">
            <%= link_to tweeet, class: "mx-1" do %>
              <i class="fa fa-link"></i>
            <% end %>
            <%= link_to edit_tweeet_path(tweeet), class: "mx-1" do %>
              <i class="fa fa-pencil"></i>
            <% end %>
            <%= link_to tweeet, method: :delete, data: { confirm: 'Are you sure you want to delete this tweet?' }, class: "mx-1" do %>
              <i class="fa fa-trash-o"></i>
            <% end %>
          </div>
        </div>
      </div>
      <hr>
    <% end %>
  </div>
</div>

app/views/tweeets/_form.html.erb
<div class="form d-flex justify-content-center">
  <%= simple_form_for(@tweeet) do |f| %>

    <%- if f.error_notification %>
      <div class="alert alert-error fade in">
        <a class="close" data-dismiss="alert" href="#">&times;</a>
        <%= f.error_notification %>
      </div>
    <%- end %>

    <div class="form-inputs">
      <%= f.input :tweeet, label: "Tweeet about it", input_html: { class: "textarea rounded" }, label_html: { class: "label d-flex flex-column" }, placeholder: "Compose a new tweeet..." %>       
    </div>
    <%= f.button :submit, class: "btn btn-primary new-tweeet-btn" %>
  <% end %>
</div>

app/views/tweeets/_who-to-follow.html.erb
<section class="who d-flex flex-column">
  <h5 class="heading">Who To Follow</h5>
    <div class="card d-flex flex-row">
      <div class="card-image">
        <img src="http://www.gravatar.com/avatar" class="card-img-top rounded-circle" alt="foto" style="width: 4rem"; >
      </div>
      <div class="card-body bio">
        <span class="firstname">James</span><br>
        <span class="lastname">Odufu</span><br>
        <span class="username">@jamezjaz</span>
      </div>
    </div>
    <div class="card d-flex flex-row">
      <div class="card-image">
        <img src="http://www.gravatar.com/avatar" class="card-img-top rounded-circle" alt="foto" style="width: 4rem"; >
      </div>
      <div class="card-body bio">
        <span class="firstname">Jessica</span><br>
        <span class="lastname">Farias</span><br>
        <span class="username">@jessyrosado</span>
      </div>
    </div>
</section>

app/views/tweeets/edit.html.erb
<h1>Editing Tweeet</h1>

<%= render 'form', tweeet: @tweeet %>

<%= link_to 'Show', @tweeet %> |
<%= link_to 'Back', tweeets_path %>

app/views/tweeets/index.html.erb
<section class="tweets container-fluid">
  <p id="notice"><%= notice %></p>

  <h1 class="title d-flex justify-content-center text-secondary">Tweeets</h1>
  
  <div class="tweet-form">
    <%= render 'form' %>
  </div>

  <div class="d-flex">
    <%= render 'feed' %>
    <%= render 'who-to-follow' %>
  </div>
</section>

app/views/tweeets/new.html.erb
<h1>New Tweeet</h1>

<%= render 'form', tweeet: @tweeet %>

<%= link_to 'Back', tweeets_path %>

app/views/tweeets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweeet:</strong>
  <%= @tweeet.tweeet %>
</p>

<%= link_to 'Edit', edit_tweeet_path(@tweeet) %> |
<%= link_to 'Back', tweeets_path %>